/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ICakeBuilder = t.iface([], {
  "tiers": t.array("Tier"),
});

const exportedTypeSuite: t.ITypeSuite = {
  ICakeBuilder,
};
export default exportedTypeSuite;
