/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IDefaultOrderForm = t.iface([], {
  "productName": "string",
  "maxColors": "number",
  "startingPrice": "number",
  "imageFilePath": "string",
  "count": "GenericFieldTypes.CountField",
  "style": "GenericFieldTypes.RadioInput",
  "colors": "GenericFieldTypes.FreeTextInput",
  "addOns": "GenericFieldTypes.FreeTextInput",
  "comments": "GenericFieldTypes.FreeTextInput",
  "nonDefaultOptions": t.union(t.array("GenericFieldTypes.ValidFormField"), "null"),
});

export const test = t.intersection("GenericFieldTypes.ValidFormField", "IDefaultOrderForm");

const exportedTypeSuite: t.ITypeSuite = {
  IDefaultOrderForm,
  test,
};
export default exportedTypeSuite;
