/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ValidFormField = t.union("RadioInput", t.intersection("FreeTextInput", t.iface([], {
  "key": "string",
})));

export const RadioOption = t.iface([], {
  "index": "number",
  "name": "string",
  "price": "number",
});

export const RadioInput = t.iface([], {
  "id": "string",
  "index": "number",
  "title": "string",
  "options": t.array("RadioOption"),
});

export const CountField = t.iface(["RadioInput"], {
  "minimum": "number",
});

export const FreeTextInput = t.iface([], {
  "id": "string",
  "index": "number",
  "title": "string",
  "description": "string",
});

export const ColorField = t.iface(["FreeTextInput"], {
  "maxColors": "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  ValidFormField,
  RadioOption,
  RadioInput,
  CountField,
  FreeTextInput,
  ColorField,
};
export default exportedTypeSuite;
