/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const LayerType = t.union(t.lit(1), t.lit(2), t.lit(3), t.lit(4));

export const DiameterType = t.union(t.lit(4), t.lit(6), t.lit(8), t.lit(10), t.lit(12));

export const TierCountType = t.union(t.lit(1), t.lit(2), t.lit(3), t.lit(4));

export const FlavorType = t.name("string");

export const LayerUpdate = t.iface([], {
  "field": t.lit('layers'),
  "value": "LayerType",
  "tierIndex": "number",
});

export const FlavorUpdate = t.iface([], {
  "field": t.lit('flavor'),
  "value": "FlavorType",
  "tierIndex": "number",
});

export const DiameterUpdate = t.iface([], {
  "field": t.lit('diameter'),
  "value": "DiameterType",
  "tierIndex": "number",
});

export const TierCountUpdate = t.iface([], {
  "field": t.lit('tiers'),
  "value": "number",
});

export const TierTypes = t.union("DiameterType", "LayerType", "FlavorType");

export const TierUpdate = t.union("LayerUpdate", "FlavorUpdate", "DiameterUpdate");

export const ICakeUpdate = t.iface([], {
  "update": t.union("TierUpdate", "TierCountUpdate"),
});

const exportedTypeSuite: t.ITypeSuite = {
  LayerType,
  DiameterType,
  TierCountType,
  FlavorType,
  LayerUpdate,
  FlavorUpdate,
  DiameterUpdate,
  TierCountUpdate,
  TierTypes,
  TierUpdate,
  ICakeUpdate,
};
export default exportedTypeSuite;
