/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IProductMetadata = t.iface([], {
  "productName": "string",
  "imageLoc": "string",
  "link": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  IProductMetadata,
};
export default exportedTypeSuite;
